// Block type registry. Each block id maps to a definition describing its
// appearance (which texture-tile faces to use) and physical properties.
//
// IDs are kept small integers so a chunk can store them in a flat Uint8Array.
// ID 0 is reserved for AIR.

export const BLOCK = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  COBBLESTONE: 4,
  WOOD: 5,        // oak log
  LEAVES: 6,
  SAND: 7,
  WATER: 8,
  BEDROCK: 9,
  PLANKS: 10,
  COAL_ORE: 11,
  IRON_ORE: 12,
  GOLD_ORE: 13,
  DIAMOND_ORE: 14,
  SNOW: 15,
  GLASS: 16,
  BRICK: 17,
  GRAVEL: 18,
  CLAY: 19,
  PUMPKIN: 20,
  CACTUS: 21,
  FLOWER_RED: 22,   // decorative, thin
  FLOWER_YELLOW: 23,
  BOOKSHELF: 24,
  OBSIDIAN: 25,
  TNT: 26,
  CRAFTING: 27,
  NETHERRACK: 28,
  RED_SAND: 29,
  TERRACOTTA: 30,
  SNOW_GRASS: 31,   // snowy grass block (grass with snow top)
  FURNACE: 32,
  PODZOL: 33,
  MYCELIUM: 34,
  JUNGLE_WOOD: 35,
  DARK_OAK_LEAVES: 36,
  SNOW_BLOCK: 37,
  BED: 38,
  PRISMITE_ORE: 39,
  CHEST: 40,
  TORCH: 41,
  SANDSTONE: 42,
  MOSSY_COBBLESTONE: 43,
  COBBLESTONE_WALL: 44,
  NETHER_BRICK: 45,
  GLASS_PANE: 46,
  HAY_BLOCK: 47,
  PRISMITE_BLOCK: 48,
  COAL_BLOCK: 49,
  IRON_BLOCK: 50,
  GOLD_BLOCK: 51,
  DIAMOND_BLOCK: 52,
  VOID_STONE: 53,
  QUARTZ_BLOCK: 54,
  BED_FOOT: 55,
  LADDER: 56,
  OAK_FENCE: 57,
  OAK_DOOR: 58,
  STONE_BUTTON: 59,
  LEVER: 60,
  OAK_SIGN: 61,
  STONE_PRESSURE_PLATE: 62,
  COPPER_ORE: 63,
  COPPER_BLOCK: 217,
  EMERALD_ORE: 64,
  CARPET: 66,
  PAINTING: 67,
  IRON_DOOR: 68,
  WOOL: 69,
  // Items that share block IDs for legacy mapping / historical reasons
  GREENSTONE_ORE: 73,
  GREENSTONE_BLOCK: 74,
  GREENSTONE_DUST: 75,
  GREENSTONE_TORCH: 76,
  GREENSTONE_LAMP: 77,
  PISTON: 78,
  STICKY_PISTON: 79,
  LAVA: 80,
  IRON_BARS: 81,
  EMBEROCK: 82,
  VOIDSTONE: 83,
  VOID_GLASS: 84,
  QUICKSAND: 85,
  BLOCKSCRAP: 86,
  STONE_BRICKS: 87,
  DEEPSLATE: 88,
  CONCRETE: 89,
  SLIME_BLOCK: 90,
  PRISMARINE: 91,
  PURPUR: 92,
  BLACKSTONE_BRICKS: 93,
  NETHER_WART: 94,
  WARPED_WART: 95,
  // Wood type variants — planks
  JUNGLE_PLANKS: 96,
  BIRCH_PLANKS: 97,
  SPRUCE_PLANKS: 98,
  DARK_OAK_PLANKS: 99,
  ACACIA_PLANKS: 100,
  // Wood type variants — logs
  BIRCH_WOOD: 101,
  SPRUCE_WOOD: 102,
  DARK_OAK_WOOD: 103,
  ACACIA_WOOD: 104,
  // Wood type variants — leaves
  BIRCH_LEAVES: 105,
  SPRUCE_LEAVES: 106,
  ACACIA_LEAVES: 107,
  VOID_PORTAL: 108,       // lit portal interior — teleports on contact
  COMPRESSED_VOIDSTONE: 109, // portal frame / crafting augment
  ECHO_ORE: 110,            // dimension ore — drops echo shards, found in ruined portals
  // New building-block variants
  CRACKED_STONE_BRICKS: 111,
  CHISELED_STONE_BRICKS: 113,
  SMOOTH_STONE: 114,
  POLISHED_BLACKSTONE: 115,
  CRACKED_BLACKSTONE_BRICKS: 116,
  GILDED_BLACKSTONE: 117,
  CHISELED_BRIMSTONE_BRICK: 118,
  CRACKED_BRIMSTONE_BRICK: 119,
  CHISELED_SANDSTONE: 120,
  CUT_SANDSTONE: 121,
  SMOOTH_SANDSTONE: 122,
  QUARTZ_BRICKS: 123,
  QUARTZ_PILLAR: 124,
  SMOOTH_QUARTZ: 125,
  PRISMARINE_BRICKS: 126,
  DARK_PRISMARINE: 127,
  // Saplings — one per tree type. Plant-style cross blocks that grow into trees.
  OAK_SAPLING: 128,
  JUNGLE_SAPLING: 129,
  BIRCH_SAPLING: 130,
  SPRUCE_SAPLING: 131,
  DARK_OAK_SAPLING: 132,
  ACACIA_SAPLING: 133,
  // Wood-type variant crafting tables
  JUNGLE_CRAFTING: 134,
  BIRCH_CRAFTING: 135,
  SPRUCE_CRAFTING: 136,
  DARK_OAK_CRAFTING: 137,
  ACACIA_CRAFTING: 138,
  ICE: 139,
  SHORT_GRASS: 140,
  TALL_GRASS: 141,
  CRYSTAL_PRISM_0: 142,
  CRYSTAL_PRISM_1: 143,
  CRYSTAL_PRISM_2: 144,
  CRYSTAL_PRISM_3: 145,
  CRYSTAL_PRISM_4: 146,
  CRYSTAL_PRISM_5: 147,
  CRYSTAL_PRISM_6: 148,
  CRYSTAL_PRISM_7: 149,
  CRYSTAL_PRISM_8: 150,
  CRYSTAL_PRISM_9: 151,
  CRYSTAL_PRISM_10: 152,
  CRYSTAL_PRISM_11: 153,
  CRYSTAL_PRISM_12: 154,
  CRYSTAL_PRISM_13: 155,
  CRYSTAL_PRISM_14: 156,
  CRYSTAL_PRISM_15: 157,
  OBSIDIAN_BRICKS: 158,
  GLOWSTONE_TILES: 159,
  BAMBOO_BLOCK: 160,
  MARBLE: 161,
  GRANITE_BRICKS: 162,
  LAVA_TILES: 163,
  CRYSTAL_ORE: 164,
  MOSSY_STONE_BRICKS: 165,
  PORTAL_PAD: 166,
  SKYGLASS: 167,
  MAGNETIC_BLOCK: 168,
  WARDENS_OBELISK: 169,
  STRUCTURE_VOID: 170,
  BARRIER: 171,
  COMMAND_BLOCK: 172,
  JUKEBOX: 173,
  FLOWER_POT: 174,
  ANVIL: 175,
  // Colored wool (176-191)
  WHITE_WOOL: 176,
  ORANGE_WOOL: 177,
  MAGENTA_WOOL: 178,
  LIGHT_BLUE_WOOL: 179,
  YELLOW_WOOL: 180,
  LIME_WOOL: 181,
  PINK_WOOL: 182,
  GRAY_WOOL: 183,
  LIGHT_GRAY_WOOL: 184,
  CYAN_WOOL: 185,
  PURPLE_WOOL: 186,
  BLUE_WOOL: 187,
  BROWN_WOOL: 188,
  GREEN_WOOL: 189,
  RED_WOOL: 190,
  BLACK_WOOL: 191,
  // Slabs (192-199)
  STONE_SLAB: 192,
  OAK_SLAB: 193,
  COBBLESTONE_SLAB: 194,
  BRICK_SLAB: 195,
  QUARTZ_SLAB: 196,
  SANDSTONE_SLAB: 197,
  NETHER_BRICK_SLAB: 198,
  DEEPSLATE_SLAB: 199,
  // Farming (200-204)
  FARMLAND: 200,
  WHEAT_0: 201,
  WHEAT_1: 202,
  WHEAT_2: 203,
  WHEAT_3: 204,
  // Campfire & lanterns (205-207)
  CAMPFIRE: 205,
  LANTERN: 206,
  SOUL_LANTERN: 207,
  // Stairs (208-215)
  STONE_STAIRS: 208,
  OAK_STAIRS: 209,
  COBBLESTONE_STAIRS: 210,
  BRICK_STAIRS: 211,
  QUARTZ_STAIRS: 212,
  SANDSTONE_STAIRS: 213,
  NETHER_BRICK_STAIRS: 214,
  DEEPSLATE_STAIRS: 215,
  // Barrel (216)
  BARREL: 216,
};

// Atlas tile name -> [tileX, tileY] in a 16x16 grid (tile 0,0 = top-left).
// tiles.js draws every named tile; this maps block faces to tile coords.
export const TILES = {
  grass_top:       [0, 0],
  grass_side:      [1, 0],
  dirt:            [2, 0],
  stone:           [3, 0],
  cobblestone:     [4, 0],
  wood_top:        [5, 0],
  wood_side:       [6, 0],
  leaves:          [7, 0],
  sand:            [8, 0],
  water:           [9, 0],
  bedrock:         [10, 0],
  planks:          [11, 0],
  coal_ore:        [12, 0],
  iron_ore:        [13, 0],
  gold_ore:        [14, 0],
  diamond_ore:     [15, 0],
  snow:            [0, 1],
  glass:           [1, 1],
  brick:           [2, 1],
  gravel:          [3, 1],
  clay:            [4, 1],
  pumpkin_top:     [5, 1],
  pumpkin_side:    [6, 1],
  pumpkin_front:   [7, 1],
  cactus_top:      [8, 1],
  cactus_side:     [9, 1],
  flower_red:      [10, 1],
  flower_yellow:   [11, 1],
  bookshelf_top:   [12, 1],
  bookshelf_side:  [13, 1],
  obsidian:        [14, 1],
  tnt_top:         [15, 1],
  tnt_side:        [0, 2],
  tnt_bottom:      [1, 2],
  crafting_top:    [2, 2],
  crafting_side:   [3, 2],
  netherrack:      [4, 2],
  red_sand:        [5, 2],
  terracotta:      [6, 2],
  snow_side:       [7, 2],   // grass-side with snow overlay
  brick_top:       [8, 2],
  furnace_top:     [9, 2],
  furnace_side:    [10, 2],
  furnace_front:   [11, 2],
  brick_furnace_top:  [9, 2],
  brick_furnace_side: [10, 2],
  brick_furnace_front:[11, 2],
  podzol_top:      [12, 2],
  podzol_side:     [13, 2],
  mycelium_top:    [14, 2],
  mycelium_side:   [15, 2],
  jungle_wood_top: [0, 3],
  jungle_wood_side:[1, 3],
  dark_leaves:     [2, 3],
  snow_block:      [3, 3],
  bed_top:         [4, 3],
  bed_side:        [5, 3],
  bed_foot:        [6, 3],
  prismite_ore:    [7, 3],
  chest_top:       [8, 3],
  chest_side:      [9, 3],
  chest_front:     [10, 3],
  torch:           [0, 4],
  sandstone:       [1, 4],
  mossy_cobblestone:[2, 4],
  cobblestone_wall: [3, 4],
  nether_brick:    [4, 4],
  glass_pane:      [5, 4],
  hay_block:       [6, 4],
  prismite_block:  [7, 4],
  coal_block:      [8, 4],
  iron_block:      [9, 4],
  gold_block:      [10, 4],
  diamond_block:   [11, 4],
  end_stone:       [12, 4],
  quartz_block:    [13, 4],
  bed_foot_top:    [14, 4],
  bed_foot_side:   [15, 4],
  ladder:          [0, 5],
  copper_ore:      [1, 5],
  copper_block:     [7, 8],
  emerald_ore:     [2, 5],
  wool:            [3, 5],
  greenstone_ore:     [4, 5],
  greenstone_block:   [5, 5],
  greenstone_lamp_off:[6, 5],
  greenstone_lamp_on: [7, 5],
  piston_top:         [8, 5],
  piston_side:        [9, 5],
  piston_bottom:      [10, 5],
  sticky_piston_top:  [11, 5],
  greenstone_torch:   [12, 5],
  greenstone_dust:    [13, 5],
  lava:               [14, 5],
  iron_bars:          [15, 5],
  emberock:           [0, 6],
  voidstone:          [1, 6],
  void_glass:         [2, 6],
  quicksand:          [3, 6],
  blockscrap:         [4, 6],
  stone_bricks:       [5, 6],
  deepslate:          [6, 6],
  deepslate_bricks:   [7, 6],
  concrete:           [8, 6],
  slime:              [9, 6],
  prismarine:         [10, 6],
  dark_prismarine:    [11, 6],
  purpur:             [12, 6],
  purpur_pillar_top:  [13, 6],
  purpur_pillar_side: [14, 6],
  blackstone_bricks:  [0, 7],
  nether_wart:        [1, 7],
  warped_wart:        [2, 7],
  // Wood type variants — planks
  jungle_planks:      [3, 7],
  birch_planks:       [4, 7],
  spruce_planks:      [5, 7],
  dark_oak_planks:    [6, 7],
  acacia_planks:      [7, 7],
  // Wood type variants — logs
  birch_wood_top:     [8, 7],
  birch_wood_side:    [9, 7],
  spruce_wood_top:    [10, 7],
  spruce_wood_side:   [11, 7],
  dark_oak_wood_top:  [12, 7],
  dark_oak_wood_side: [13, 7],
  acacia_wood_top:    [14, 7],
  acacia_wood_side:   [15, 7],
  // Wood type variants — leaves
  birch_leaves:       [0, 8],
  spruce_leaves:      [1, 8],
  acacia_leaves:      [2, 8],
  // Shattered Echo Dimension tiles
  void_portal:        [3, 8],
  compressed_voidstone:[4, 8],
  echo_ore:       [5, 8],
  cracked_stone_bricks: [0, 9],
  mossy_stone_bricks: [1, 9],
  chiseled_stone_bricks: [2, 9],
  smooth_stone: [3, 9],
  polished_blackstone: [4, 9],
  cracked_blackstone_bricks: [5, 9],
  gilded_blackstone: [6, 9],
  chiseled_brimstone_brick: [7, 9],
  cracked_brimstone_brick: [8, 9],
  chiseled_sandstone: [9, 9],
  cut_sandstone: [10, 9],
  smooth_sandstone: [11, 9],
  quartz_bricks: [12, 9],
  quartz_pillar_top: [13, 9],
  quartz_pillar_side: [14, 9],
  smooth_quartz: [15, 9],
  prismarine_bricks: [0, 10],
  // Saplings
  sapling_oak:       [1, 10],
  sapling_jungle:    [2, 10],
  sapling_birch:     [3, 10],
  sapling_spruce:    [4, 10],
  sapling_dark_oak:  [5, 10],
  sapling_acacia:    [6, 10],
  // Wood-type variant crafting tables
  jungle_crafting_top:   [7, 10],
  jungle_crafting_side:  [8, 10],
  birch_crafting_top:    [9, 10],
  birch_crafting_side:   [10, 10],
  spruce_crafting_top:   [11, 10],
  spruce_crafting_side:  [12, 10],
  dark_oak_crafting_top: [13, 10],
  dark_oak_crafting_side:[14, 10],
  acacia_crafting_top:   [15, 10],
  acacia_crafting_side:  [0, 11],
  ice:                   [1, 11],
   short_grass:            [2, 11],
   tall_grass:             [3, 11],
   stone_furnace_top:      [4, 11],
   stone_furnace_front:    [5, 11],

  // Crystal prisms (16 colors) — light-emitting decorative blocks (row 12).
  crystal_prism_0:       [0, 12],
  crystal_prism_1:       [1, 12],
  crystal_prism_2:       [2, 12],
  crystal_prism_3:       [3, 12],
  crystal_prism_4:       [4, 12],
  crystal_prism_5:       [5, 12],
  crystal_prism_6:       [6, 12],
  crystal_prism_7:       [7, 12],
  crystal_prism_8:       [8, 12],
  crystal_prism_9:       [9, 12],
  crystal_prism_10:      [10, 12],
  crystal_prism_11:      [11, 12],
  crystal_prism_12:      [12, 12],
  crystal_prism_13:      [13, 12],
  crystal_prism_14:      [14, 12],
  crystal_prism_15:      [15, 12],

  // Additional original blocks (row 13).
  obsidian_bricks:       [0, 13],
  glowstone_tiles:       [1, 13],
  bamboo_block:          [2, 13],
  marble:                [3, 13],
  granite_bricks:        [4, 13],
  lava_tiles:            [5, 13],
  crystal_ore:           [6, 13],
  mossy_stone_bricks:    [7, 13],
  portal_pad:            [8, 13],
  skyglass:              [9, 13],
  magnetic_block:        [10, 13],
  wardens_obelisk:       [11, 13],
  structure_void:        [12, 13],
  barrier:               [13, 13],
  command_block:         [14, 13],
  jukebox:               [15, 13],
  flower_pot:            [0, 14],

  // Multi-face tiles for the blocks above (rows 14–15).
  bamboo_top:            [1, 14],
  bamboo_side:           [2, 14],
  portal_pad_top:        [3, 14],
  portal_pad_side:       [4, 14],
  wardens_obelisk_top:   [5, 14],
  wardens_obelisk_side:  [6, 14],
  command_block_top:     [7, 14],
  command_block_side:    [8, 14],
  jukebox_top:           [9, 14],
  jukebox_side:          [10, 14],
  flower_pot_top:        [11, 14],
  flower_pot_bottom:     [12, 14],
  flower_pot_side:       [13, 14],
  // Colored wool tiles (row 14 cols 14-15, row 15 cols 0-13)
  white_wool:            [14, 14],
  orange_wool:           [15, 14],
  magenta_wool:          [0, 15],
  light_blue_wool:       [1, 15],
  yellow_wool:           [2, 15],
  lime_wool:             [3, 15],
  pink_wool:             [4, 15],
  gray_wool:             [5, 15],
  light_gray_wool:       [6, 15],
  cyan_wool:             [7, 15],
  purple_wool:           [8, 15],
  blue_wool:             [9, 15],
  brown_wool:            [10, 15],
  green_wool:            [11, 15],
  red_wool:              [12, 15],
  black_wool:            [13, 15],
  // Farming tiles (row 11, cols 6-10)
  farmland:              [6, 11],
  wheat_0:               [7, 11],
  wheat_1:               [8, 11],
  wheat_2:               [9, 11],
  wheat_3:               [10, 11],
  // Campfire & lanterns (row 11, cols 11-13)
  campfire:              [11, 11],
  lantern:               [12, 11],
  soul_lantern:          [13, 11],
  // Stairs reuse existing textures (no new tiles needed)
  barrel:                [14, 11],
};

// Per-block definition. `faces` is [top, bottom, side] tile names, or a single
// tile name used for all faces. `solid` affects collision; `transparent`
// means neighbour faces behind it still render (leaves/glass/water/plants).
//
// Survival metadata (all optional):
//   hardness  : seconds to break by hand (≈ BlockForge values). Default 0.
//   tool      : 'pickaxe' | 'axe' | 'shovel' | null — the tool that gives full
//               speed and (for harvestable blocks) the block drop.
//   harvest   : 0..4 — minimum tool tier needed for the drop to actually spawn.
//               0 = drops by hand; 1=wood/gold; 2=stone; 3=iron; 4=diamond.
//   drop      : block id OR an item id (from items.js) to drop when broken.
//               If omitted, the block drops itself (its own id). Use 0 to drop
//               nothing (e.g. glass). Plants drop themselves.
export const BLOCKS = {
  [BLOCK.AIR]:        { name: 'Air', solid: false, transparent: true, liquid: false },
  [BLOCK.GRASS]:      { name: 'Grass', solid: true, hardness: 0.6, tool: 'shovel', drop: BLOCK.DIRT, faces: { top: 'grass_top', bottom: 'dirt', side: 'grass_side' } },
  [BLOCK.DIRT]:       { name: 'Dirt', solid: true, hardness: 0.5, tool: 'shovel', faces: 'dirt' },
  [BLOCK.STONE]:      { name: 'Stone', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, drop: BLOCK.COBBLESTONE, faces: 'stone' },
  [BLOCK.COBBLESTONE]:{ name: 'Cobblestone', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'cobblestone' },
  [BLOCK.WOOD]:       { name: 'Oak Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.WOOD, faces: { top: 'wood_top', bottom: 'wood_top', side: 'wood_side' } },
  [BLOCK.LEAVES]:     { name: 'Leaves', solid: true, transparent: true, cutout: true, hardness: 0.2, faces: 'leaves' },
  [BLOCK.SAND]:       { name: 'Sand', solid: true, hardness: 0.5, tool: 'shovel', faces: 'sand' },
  [BLOCK.WATER]:      { name: 'Water', solid: false, transparent: true, liquid: true, drop: 0, faces: 'water' },
  [BLOCK.BEDROCK]:    { name: 'Bedrock', solid: true, hardness: -1, unbreakable: true, faces: 'bedrock' },
  [BLOCK.PLANKS]:     { name: 'Oak Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'planks' },
  [BLOCK.COAL_ORE]:   { name: 'Coal Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, drop: 257 /* COAL item */, faces: 'coal_ore' },
  [BLOCK.IRON_ORE]:   { name: 'Iron Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 2, drop: 259 /* IRON_INGOT item */, faces: 'iron_ore' },
  [BLOCK.GOLD_ORE]:   { name: 'Gold Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 3, drop: 260 /* GOLD_INGOT item */, faces: 'gold_ore' },
  [BLOCK.DIAMOND_ORE]:{ name: 'Diamond Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 3, drop: 261 /* DIAMOND item */, faces: 'diamond_ore' },
  [BLOCK.SNOW]:       { name: 'Snow', solid: true, hardness: 0.2, tool: 'shovel', faces: 'snow' },
  [BLOCK.GLASS]:      { name: 'Glass', solid: true, transparent: true, hardness: 0.3, drop: 0, faces: 'glass' },
  [BLOCK.BRICK]:      { name: 'Bricks', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'brick' },
  [BLOCK.GRAVEL]:     { name: 'Gravel', solid: true, hardness: 0.6, tool: 'shovel', faces: 'gravel' },
  [BLOCK.CLAY]:       { name: 'Clay', solid: true, hardness: 0.6, tool: 'shovel', faces: 'clay' },
  [BLOCK.PUMPKIN]:    { name: 'Pumpkin', solid: true, hardness: 1.0, tool: 'axe', faces: { top: 'pumpkin_top', bottom: 'pumpkin_top', side: 'pumpkin_side' } },
  [BLOCK.CACTUS]:     { name: 'Cactus', solid: true, hardness: 0.4, faces: { top: 'cactus_top', bottom: 'cactus_top', side: 'cactus_side' } },
  [BLOCK.FLOWER_RED]: { name: 'Poppy', solid: false, transparent: true, plant: true, hardness: 0, faces: 'flower_red' },
  [BLOCK.FLOWER_YELLOW]:{ name: 'Dandelion', solid: false, transparent: true, plant: true, hardness: 0, faces: 'flower_yellow' },
  [BLOCK.BOOKSHELF]:  { name: 'Bookshelf', solid: true, hardness: 1.5, tool: 'axe', faces: { top: 'planks', bottom: 'planks', side: 'bookshelf_side' } },
  [BLOCK.OBSIDIAN]:   { name: 'Obsidian', solid: true, hardness: 50, tool: 'pickaxe', harvest: 4, faces: 'obsidian' },
  [BLOCK.TNT]:        { name: 'TNT', solid: true, hardness: 0, faces: { top: 'tnt_top', bottom: 'tnt_bottom', side: 'tnt_side' } },
  [BLOCK.CRAFTING]:   { name: 'Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'crafting_top', bottom: 'planks', side: 'crafting_side' } },
  [BLOCK.NETHERRACK]: { name: 'Brimstone', solid: true, hardness: 0.4, tool: 'pickaxe', harvest: 1, faces: 'netherrack' },
  [BLOCK.RED_SAND]:   { name: 'Red Sand', solid: true, hardness: 0.5, tool: 'shovel', faces: 'red_sand' },
  [BLOCK.TERRACOTTA]: { name: 'Terracotta', solid: true, hardness: 1.25, tool: 'pickaxe', harvest: 1, faces: 'terracotta' },
  [BLOCK.SNOW_GRASS]: { name: 'Snowy Grass', solid: true, hardness: 0.6, tool: 'shovel', drop: BLOCK.DIRT, faces: { top: 'snow', bottom: 'dirt', side: 'snow_side' } },
  [BLOCK.FURNACE]:    { name: 'Stone Furnace', solid: true, hardness: 3.5, tool: 'pickaxe', harvest: 1, faces: { top: 'stone_furnace_top', bottom: 'stone_furnace_top', side: 'stone_furnace_front' } },
  [BLOCK.PODZOL]:     { name: 'Podzol', solid: true, hardness: 0.6, tool: 'shovel', drop: BLOCK.DIRT, faces: { top: 'podzol_top', bottom: 'dirt', side: 'podzol_side' } },
  [BLOCK.MYCELIUM]:   { name: 'Mycelium', solid: true, hardness: 0.6, tool: 'shovel', drop: BLOCK.DIRT, faces: { top: 'mycelium_top', bottom: 'dirt', side: 'mycelium_side' } },
  [BLOCK.JUNGLE_WOOD]:{ name: 'Jungle Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.JUNGLE_WOOD, faces: { top: 'jungle_wood_top', bottom: 'jungle_wood_top', side: 'jungle_wood_side' } },
  [BLOCK.DARK_OAK_LEAVES]:{ name: 'Dark Oak Leaves', solid: true, transparent: true, cutout: true, hardness: 0.2, faces: 'dark_leaves' },
  [BLOCK.SNOW_BLOCK]: { name: 'Snow Block', solid: true, hardness: 0.2, tool: 'shovel', faces: 'snow_block' },
  [BLOCK.BED]:        { name: 'Bed', bed: true, solid: true, hardness: 0.2, drop: 285 /* BED */, faces: { top: 'bed_top', bottom: 'planks', side: 'bed_side' } },
  [BLOCK.BED_FOOT]:   { name: 'Bed', bed: true, solid: true, hardness: 0.2, drop: 285 /* BED */, faces: { top: 'bed_foot_top', bottom: 'planks', side: 'bed_foot_side' } },
  [BLOCK.PRISMITE_ORE]: { name: 'Prismite Ore', solid: true, hardness: 50, tool: 'pickaxe', harvest: 4, drop: 287 /* PRISMITE item */, faces: 'prismite_ore' },
  [BLOCK.CHEST]:      { name: 'Chest', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'chest_top', bottom: 'planks', side: 'chest_side', front: 'chest_front' } },
  [BLOCK.TORCH]:      { name: 'Torch', solid: false, transparent: true, plant: true, hardness: 0, luminance: 14, drop: 41, faces: 'torch' },
  [BLOCK.SANDSTONE]:  { name: 'Sandstone', solid: true, hardness: 0.8, tool: 'pickaxe', faces: 'sandstone' },
  [BLOCK.MOSSY_COBBLESTONE]: { name: 'Mossy Cobblestone', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'mossy_cobblestone' },
  [BLOCK.COBBLESTONE_WALL]: { name: 'Cobblestone Wall', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'cobblestone_wall' },
  [BLOCK.NETHER_BRICK]: { name: 'Brimstone Bricks', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'nether_brick' },
  [BLOCK.GLASS_PANE]: { name: 'Glass Pane', solid: true, transparent: true, hardness: 0.3, drop: 0, faces: 'glass_pane' },
  [BLOCK.HAY_BLOCK]:  { name: 'Hay Bale', solid: true, hardness: 0.5, tool: 'hoe', faces: { top: 'hay_block', bottom: 'hay_block', side: 'hay_block' } },
  [BLOCK.PRISMITE_BLOCK]: { name: 'Prismite Block', solid: true, hardness: 4, tool: 'pickaxe', harvest: 3, faces: 'prismite_block' },
  [BLOCK.COAL_BLOCK]: { name: 'Block of Coal', solid: true, hardness: 5, tool: 'pickaxe', harvest: 1, faces: 'coal_block' },
  [BLOCK.IRON_BLOCK]: { name: 'Block of Iron', solid: true, hardness: 5, tool: 'pickaxe', harvest: 2, faces: 'iron_block' },
  [BLOCK.GOLD_BLOCK]: { name: 'Block of Gold', solid: true, hardness: 5, tool: 'pickaxe', harvest: 2, faces: 'gold_block' },
  [BLOCK.DIAMOND_BLOCK]: { name: 'Block of Diamond', solid: true, hardness: 5, tool: 'pickaxe', harvest: 3, faces: 'diamond_block' },
  [BLOCK.VOID_STONE]:  { name: 'Void Stone', solid: true, hardness: 3, tool: 'pickaxe', harvest: 1, faces: 'end_stone' },
  [BLOCK.QUARTZ_BLOCK]: { name: 'Quartz Block', solid: true, hardness: 1, tool: 'pickaxe', harvest: 1, faces: 'quartz_block' },
  [BLOCK.LADDER]:      { name: 'Ladder', solid: false, transparent: true, plant: true, hardness: 0.4, faces: 'ladder' },
  [BLOCK.OAK_FENCE]:   { name: 'Oak Fence', solid: true, hardness: 2.0, tool: 'axe', faces: 'planks' },
  [BLOCK.OAK_DOOR]:    { name: 'Oak Door', solid: false, transparent: true, hardness: 3.0, tool: 'axe', faces: 'planks' },
  [BLOCK.STONE_BUTTON]:{ name: 'Stone Button', solid: false, transparent: true, plant: true, hardness: 0.5, faces: 'stone' },
  [BLOCK.LEVER]:       { name: 'Lever', solid: false, transparent: true, plant: true, hardness: 0.5, faces: 'stone' },
  [BLOCK.OAK_SIGN]:    { name: 'Oak Sign', solid: false, transparent: true, plant: true, hardness: 1.0, tool: 'axe', faces: 'planks' },
  [BLOCK.STONE_PRESSURE_PLATE]: { name: 'Stone Pressure Plate', solid: false, transparent: true, plant: true, hardness: 0.5, faces: 'stone' },
  [BLOCK.COPPER_ORE]: { name: 'Copper Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, drop: 304 /* COPPER_INGOT */, faces: 'copper_ore' },
  [BLOCK.COPPER_BLOCK]: { name: 'Copper Block', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'copper_block' },
  [BLOCK.EMERALD_ORE]: { name: 'Emerald Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 2, drop: 305 /* EMERALD */, faces: 'emerald_ore' },
  [BLOCK.FLOWER_POT]:  { name: 'Flower Pot', solid: false, transparent: true, plant: true, hardness: 0, faces: 'terracotta' },
  [BLOCK.CARPET]:      { name: 'Carpet', solid: false, transparent: true, plant: true, hardness: 0.1, faces: 'wool' },
  [BLOCK.PAINTING]:    { name: 'Painting', solid: false, transparent: true, plant: true, hardness: 0, faces: 'planks' },
  [BLOCK.IRON_DOOR]:   { name: 'Iron Door', solid: false, transparent: true, hardness: 5.0, tool: 'pickaxe', harvest: 1, faces: 'iron_block' },
  [BLOCK.WOOL]:        { name: 'Wool', solid: true, hardness: 0.8, faces: 'wool' },
  [BLOCK.GREENSTONE_ORE]: { name: 'Greenstone Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, drop: 314 /* GREENSTONE_DUST */, faces: 'greenstone_ore' },
  [BLOCK.GREENSTONE_BLOCK]: { name: 'Block of Greenstone', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'greenstone_block', power: 15 },
  [BLOCK.GREENSTONE_DUST]: { name: 'Greenstone Dust', solid: false, transparent: true, plant: true, hardness: 0, faces: 'greenstone_dust', maxSignal: 15 },
  [BLOCK.GREENSTONE_TORCH]: { name: 'Greenstone Torch', solid: false, transparent: true, plant: true, hardness: 0, luminance: 7, drop: BLOCK.GREENSTONE_TORCH, faces: 'greenstone_torch', power: 15 },
  [BLOCK.GREENSTONE_LAMP]: { name: 'Greenstone Lamp', solid: true, hardness: 0.3, faces: { top: 'greenstone_lamp_off', bottom: 'greenstone_lamp_off', side: 'greenstone_lamp_off' } },
  [BLOCK.PISTON]:    { name: 'Piston', solid: true, hardness: 1.5, tool: 'axe', faces: { top: 'piston_top', bottom: 'piston_bottom', side: 'piston_side' } },
  [BLOCK.STICKY_PISTON]: { name: 'Sticky Piston', solid: true, hardness: 1.5, tool: 'axe', faces: { top: 'sticky_piston_top', bottom: 'piston_bottom', side: 'piston_side' } },
  [BLOCK.LAVA]:       { name: 'Lava', solid: false, transparent: true, liquid: true, luminance: 15, faces: 'lava' },
  [BLOCK.IRON_BARS]:  { name: 'Iron Bars', solid: true, transparent: true, hardness: 5, tool: 'pickaxe', faces: 'iron_bars' },
  [BLOCK.EMBEROCK]:   { name: 'Emberock', solid: true, hardness: 0.4, tool: 'pickaxe', harvest: 1, faces: 'emberock' },
  [BLOCK.VOIDSTONE]:  { name: 'Voidstone', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'voidstone' },
  [BLOCK.VOID_GLASS]: { name: 'Void Glass', solid: true, transparent: true, hardness: 0.3, drop: 0, faces: 'void_glass' },
  [BLOCK.QUICKSAND]:  { name: 'Quicksand', solid: true, hardness: 0.5, tool: 'shovel', faces: 'quicksand' },
  [BLOCK.BLOCKSCRAP]: { name: 'Block Scrap', solid: true, hardness: 1.5, tool: 'pickaxe', faces: 'blockscrap' },
  [BLOCK.STONE_BRICKS]: { name: 'Stone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'stone_bricks' },
  [BLOCK.DEEPSLATE]:  { name: 'Deepslate', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'deepslate' },
  [BLOCK.CONCRETE]:   { name: 'Concrete', solid: true, hardness: 1.8, tool: 'pickaxe', faces: 'concrete' },
  [BLOCK.SLIME_BLOCK]: { name: 'Slime Block', solid: true, transparent: true, hardness: 0.0, faces: 'slime' },
  [BLOCK.PRISMARINE]: { name: 'Prismarine', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'prismarine' },
  [BLOCK.PURPUR]:     { name: 'Purpur Block', solid: true, hardness: 1.5, tool: 'pickaxe', faces: { top: 'purpur', bottom: 'purpur', side: 'purpur_pillar_side' } },
  [BLOCK.BLACKSTONE_BRICKS]: { name: 'Blackstone Bricks', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'blackstone_bricks' },
  [BLOCK.NETHER_WART]: { name: 'Crimson Wart Block', solid: true, hardness: 1.0, faces: 'nether_wart' },
  [BLOCK.WARPED_WART]: { name: 'Warped Wart Block', solid: true, hardness: 1.0, faces: 'warped_wart' },
  // Wood type variant planks
  [BLOCK.JUNGLE_PLANKS]:  { name: 'Jungle Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'jungle_planks' },
  [BLOCK.BIRCH_PLANKS]:   { name: 'Birch Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'birch_planks' },
  [BLOCK.SPRUCE_PLANKS]:  { name: 'Spruce Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'spruce_planks' },
  [BLOCK.DARK_OAK_PLANKS]:{ name: 'Dark Oak Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'dark_oak_planks' },
  [BLOCK.ACACIA_PLANKS]:  { name: 'Acacia Planks', solid: true, hardness: 2.0, tool: 'axe', faces: 'acacia_planks' },
  // Wood type variant logs
  [BLOCK.BIRCH_WOOD]:     { name: 'Birch Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.BIRCH_WOOD, faces: { top: 'birch_wood_top', bottom: 'birch_wood_top', side: 'birch_wood_side' } },
  [BLOCK.SPRUCE_WOOD]:    { name: 'Spruce Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.SPRUCE_WOOD, faces: { top: 'spruce_wood_top', bottom: 'spruce_wood_top', side: 'spruce_wood_side' } },
  [BLOCK.DARK_OAK_WOOD]:  { name: 'Dark Oak Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.DARK_OAK_WOOD, faces: { top: 'dark_oak_wood_top', bottom: 'dark_oak_wood_top', side: 'dark_oak_wood_side' } },
  [BLOCK.ACACIA_WOOD]:    { name: 'Acacia Log', solid: true, hardness: 2.0, tool: 'axe', drop: BLOCK.ACACIA_WOOD, faces: { top: 'acacia_wood_top', bottom: 'acacia_wood_top', side: 'acacia_wood_side' } },
  // Wood type variant leaves
  [BLOCK.BIRCH_LEAVES]:   { name: 'Birch Leaves', solid: true, transparent: true, cutout: true, hardness: 0.2, faces: 'birch_leaves' },
  [BLOCK.SPRUCE_LEAVES]:  { name: 'Spruce Leaves', solid: true, transparent: true, cutout: true, hardness: 0.2, faces: 'spruce_leaves' },
  [BLOCK.ACACIA_LEAVES]:  { name: 'Acacia Leaves', solid: true, transparent: true, cutout: true, hardness: 0.2, faces: 'acacia_leaves' },
  // Shattered Echo Dimension
  [BLOCK.VOID_PORTAL]: { name: 'Void Portal', solid: false, transparent: true, cutout: true, hardness: 0, unbreakable: true, drop: 0, faces: 'void_portal', portal: true },
  [BLOCK.COMPRESSED_VOIDSTONE]: { name: 'Compressed Voidstone', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'compressed_voidstone' },
  [BLOCK.ECHO_ORE]: { name: 'Echo Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'echo_ore', drop: 710 },
  [BLOCK.CRACKED_STONE_BRICKS]: { name: 'Cracked Stone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'cracked_stone_bricks' },
  [BLOCK.MOSSY_STONE_BRICKS]: { name: 'Mossy Stone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'mossy_stone_bricks' },
  [BLOCK.CHISELED_STONE_BRICKS]: { name: 'Chiseled Stone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'chiseled_stone_bricks' },
  [BLOCK.SMOOTH_STONE]: { name: 'Smooth Stone', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'smooth_stone' },
  [BLOCK.POLISHED_BLACKSTONE]: { name: 'Polished Blackstone', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'polished_blackstone' },
  [BLOCK.CRACKED_BLACKSTONE_BRICKS]: { name: 'Cracked Blackstone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'cracked_blackstone_bricks' },
  [BLOCK.GILDED_BLACKSTONE]: { name: 'Gilded Blackstone', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'gilded_blackstone' },
  [BLOCK.CHISELED_BRIMSTONE_BRICK]: { name: 'Chiseled Brimstone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'chiseled_brimstone_brick' },
  [BLOCK.CRACKED_BRIMSTONE_BRICK]: { name: 'Cracked Brimstone Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'cracked_brimstone_brick' },
  [BLOCK.CHISELED_SANDSTONE]: { name: 'Chiseled Sandstone', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'chiseled_sandstone' },
  [BLOCK.CUT_SANDSTONE]: { name: 'Cut Sandstone', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'cut_sandstone' },
  [BLOCK.SMOOTH_SANDSTONE]: { name: 'Smooth Sandstone', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'smooth_sandstone' },
  [BLOCK.QUARTZ_BRICKS]: { name: 'Quartz Bricks', solid: true, hardness: 1, tool: 'pickaxe', harvest: 1, faces: 'quartz_bricks' },
  [BLOCK.QUARTZ_PILLAR]: { name: 'Quartz Pillar', solid: true, hardness: 1, tool: 'pickaxe', harvest: 1, faces: { top: 'quartz_pillar_top', bottom: 'quartz_pillar_top', side: 'quartz_pillar_side' } },
  [BLOCK.SMOOTH_QUARTZ]: { name: 'Smooth Quartz', solid: true, hardness: 1, tool: 'pickaxe', harvest: 1, faces: 'smooth_quartz' },
  [BLOCK.PRISMARINE_BRICKS]: { name: 'Prismarine Bricks', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'prismarine_bricks' },
  [BLOCK.DARK_PRISMARINE]: { name: 'Dark Prismarine', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'dark_prismarine' },
  // Saplings — thin cross plants (like flowers) that grow into trees.
  [BLOCK.OAK_SAPLING]:      { name: 'Oak Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_oak' },
  [BLOCK.JUNGLE_SAPLING]:   { name: 'Jungle Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_jungle' },
  [BLOCK.BIRCH_SAPLING]:    { name: 'Birch Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_birch' },
  [BLOCK.SPRUCE_SAPLING]:   { name: 'Spruce Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_spruce' },
  [BLOCK.DARK_OAK_SAPLING]: { name: 'Dark Oak Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_dark_oak' },
  [BLOCK.ACACIA_SAPLING]:   { name: 'Acacia Sapling', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, faces: 'sapling_acacia' },
  // Wood-type variant crafting tables
  [BLOCK.JUNGLE_CRAFTING]:   { name: 'Jungle Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'jungle_crafting_top', bottom: 'jungle_planks', side: 'jungle_crafting_side' } },
  [BLOCK.BIRCH_CRAFTING]:    { name: 'Birch Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'birch_crafting_top', bottom: 'birch_planks', side: 'birch_crafting_side' } },
  [BLOCK.SPRUCE_CRAFTING]:   { name: 'Spruce Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'spruce_crafting_top', bottom: 'spruce_planks', side: 'spruce_crafting_side' } },
  [BLOCK.DARK_OAK_CRAFTING]: { name: 'Dark Oak Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'dark_oak_crafting_top', bottom: 'dark_oak_planks', side: 'dark_oak_crafting_side' } },
  [BLOCK.ACACIA_CRAFTING]:   { name: 'Acacia Workbench', solid: true, hardness: 2.5, tool: 'axe', faces: { top: 'acacia_crafting_top', bottom: 'acacia_planks', side: 'acacia_crafting_side' } },
  [BLOCK.ICE]:              { name: 'Ice', solid: true, transparent: true, hardness: 0.5, faces: 'ice' },
  [BLOCK.SHORT_GRASS]:      { name: 'Short Grass', solid: false, transparent: true, plant: true, hardness: 0, faces: 'short_grass' },
  [BLOCK.TALL_GRASS]:       { name: 'Tall Grass', solid: false, transparent: true, plant: true, hardness: 0, faces: 'tall_grass' },

  // ── Crystal prisms: 16 colors, each a full light source ──
  [BLOCK.CRYSTAL_PRISM_0]:  { name: 'Crimson Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_0' },
  [BLOCK.CRYSTAL_PRISM_1]:  { name: 'Amber Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_1' },
  [BLOCK.CRYSTAL_PRISM_2]:  { name: 'Gold Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_2' },
  [BLOCK.CRYSTAL_PRISM_3]:  { name: 'Lime Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_3' },
  [BLOCK.CRYSTAL_PRISM_4]:  { name: 'Forest Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_4' },
  [BLOCK.CRYSTAL_PRISM_5]:  { name: 'Teal Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_5' },
  [BLOCK.CRYSTAL_PRISM_6]:  { name: 'Aqua Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_6' },
  [BLOCK.CRYSTAL_PRISM_7]:  { name: 'Azure Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_7' },
  [BLOCK.CRYSTAL_PRISM_8]:  { name: 'Indigo Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_8' },
  [BLOCK.CRYSTAL_PRISM_9]:  { name: 'Violet Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_9' },
  [BLOCK.CRYSTAL_PRISM_10]: { name: 'Magenta Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_10' },
  [BLOCK.CRYSTAL_PRISM_11]: { name: 'Rose Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_11' },
  [BLOCK.CRYSTAL_PRISM_12]: { name: 'Pearl Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_12' },
  [BLOCK.CRYSTAL_PRISM_13]: { name: 'Slate Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_13' },
  [BLOCK.CRYSTAL_PRISM_14]: { name: 'Obsidian Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_14' },
  [BLOCK.CRYSTAL_PRISM_15]: { name: 'Umber Prism', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 15, faces: 'crystal_prism_15' },

  [BLOCK.OBSIDIAN_BRICKS]:  { name: 'Obsidian Bricks', solid: true, hardness: 25, tool: 'pickaxe', harvest: 3, faces: 'obsidian_bricks' },
  [BLOCK.GLOWSTONE_TILES]:  { name: 'Lumite Tiles', solid: true, hardness: 1.0, tool: 'pickaxe', harvest: 2, luminance: 14, faces: 'glowstone_tiles' },
  [BLOCK.BAMBOO_BLOCK]:     { name: 'Bamboo Block', solid: true, hardness: 1.5, tool: 'axe', faces: { top: 'bamboo_top', bottom: 'bamboo_top', side: 'bamboo_side' } },
  [BLOCK.MARBLE]:           { name: 'Marble', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'marble' },
  [BLOCK.GRANITE_BRICKS]:   { name: 'Granite Bricks', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'granite_bricks' },
  [BLOCK.LAVA_TILES]:       { name: 'Magma Tiles', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'lava_tiles', lightEmit: 6, damage: 1 },
  [BLOCK.CRYSTAL_ORE]:      { name: 'Crystal Ore', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 2, drop: 287, faces: 'crystal_ore', luminance: 6 },
  [BLOCK.MOSSY_STONE_BRICKS]: { name: 'Mossy Stone Bricks', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'mossy_stone_bricks' },
  [BLOCK.PORTAL_PAD]:       { name: 'Portal Pad', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 2, faces: { top: 'portal_pad_top', bottom: 'obsidian_bricks', side: 'portal_pad_side' } },
  [BLOCK.SKYGLASS]:         { name: 'Skyglass', solid: true, transparent: true, hardness: 0.4, drop: 0, faces: 'skyglass' },
  [BLOCK.MAGNETIC_BLOCK]:   { name: 'Magnetstone', solid: true, hardness: 2.5, tool: 'pickaxe', harvest: 2, faces: 'magnetic_block' },
  [BLOCK.WARDENS_OBELISK]:  { name: "Warden's Obelisk", solid: true, hardness: 50, unbreakable: true, faces: { top: 'wardens_obelisk_top', bottom: 'obsidian_bricks', side: 'wardens_obelisk_side' } },
  [BLOCK.STRUCTURE_VOID]:   { name: 'Structure Void', solid: false, transparent: true, hardness: 0, drop: 0, faces: 'structure_void' },
  [BLOCK.BARRIER]:          { name: 'Barrier', solid: true, transparent: true, hardness: -1, unbreakable: true, faces: 'barrier', creativeOnly: true },
  [BLOCK.COMMAND_BLOCK]:    { name: 'Command Block', solid: true, hardness: -1, unbreakable: true, faces: { top: 'command_block_top', bottom: 'command_block_top', side: 'command_block_side' }, creativeOnly: true },
  [BLOCK.JUKEBOX]:          { name: 'Jukebox', solid: true, hardness: 2.0, tool: 'axe', faces: { top: 'jukebox_top', bottom: 'planks', side: 'jukebox_side' } },
  [BLOCK.FLOWER_POT]:       { name: 'Flower Pot', solid: true, hardness: 0.4, tool: 'pickaxe', faces: { top: 'flower_pot_top', bottom: 'flower_pot_bottom', side: 'flower_pot_side' } },
  [BLOCK.ANVIL]:            { name: 'Anvil', solid: true, hardness: 5.0, tool: 'pickaxe', harvest: 2, faces: 'iron_block' },
  // Colored wool blocks
  [BLOCK.WHITE_WOOL]:     { name: 'White Wool', solid: true, hardness: 0.8, faces: 'white_wool' },
  [BLOCK.ORANGE_WOOL]:    { name: 'Orange Wool', solid: true, hardness: 0.8, faces: 'orange_wool' },
  [BLOCK.MAGENTA_WOOL]:   { name: 'Magenta Wool', solid: true, hardness: 0.8, faces: 'magenta_wool' },
  [BLOCK.LIGHT_BLUE_WOOL]:{ name: 'Light Blue Wool', solid: true, hardness: 0.8, faces: 'light_blue_wool' },
  [BLOCK.YELLOW_WOOL]:    { name: 'Yellow Wool', solid: true, hardness: 0.8, faces: 'yellow_wool' },
  [BLOCK.LIME_WOOL]:      { name: 'Lime Wool', solid: true, hardness: 0.8, faces: 'lime_wool' },
  [BLOCK.PINK_WOOL]:      { name: 'Pink Wool', solid: true, hardness: 0.8, faces: 'pink_wool' },
  [BLOCK.GRAY_WOOL]:      { name: 'Gray Wool', solid: true, hardness: 0.8, faces: 'gray_wool' },
  [BLOCK.LIGHT_GRAY_WOOL]:{ name: 'Light Gray Wool', solid: true, hardness: 0.8, faces: 'light_gray_wool' },
  [BLOCK.CYAN_WOOL]:      { name: 'Cyan Wool', solid: true, hardness: 0.8, faces: 'cyan_wool' },
  [BLOCK.PURPLE_WOOL]:    { name: 'Purple Wool', solid: true, hardness: 0.8, faces: 'purple_wool' },
  [BLOCK.BLUE_WOOL]:      { name: 'Blue Wool', solid: true, hardness: 0.8, faces: 'blue_wool' },
  [BLOCK.BROWN_WOOL]:     { name: 'Brown Wool', solid: true, hardness: 0.8, faces: 'brown_wool' },
  [BLOCK.GREEN_WOOL]:     { name: 'Green Wool', solid: true, hardness: 0.8, faces: 'green_wool' },
  [BLOCK.RED_WOOL]:       { name: 'Red Wool', solid: true, hardness: 0.8, faces: 'red_wool' },
  [BLOCK.BLACK_WOOL]:     { name: 'Black Wool', solid: true, hardness: 0.8, faces: 'black_wool' },
  // Slabs (bottom-half only, height 0.5)
  [BLOCK.STONE_SLAB]:        { name: 'Stone Slab', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'stone', slab: true },
  [BLOCK.OAK_SLAB]:          { name: 'Oak Slab', solid: true, hardness: 2.0, tool: 'axe', faces: 'planks', slab: true },
  [BLOCK.COBBLESTONE_SLAB]:  { name: 'Cobblestone Slab', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'cobblestone', slab: true },
  [BLOCK.BRICK_SLAB]:        { name: 'Brick Slab', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'brick', slab: true },
  [BLOCK.QUARTZ_SLAB]:       { name: 'Quartz Slab', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'quartz_block', slab: true },
  [BLOCK.SANDSTONE_SLAB]:    { name: 'Sandstone Slab', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'sandstone', slab: true },
  [BLOCK.NETHER_BRICK_SLAB]: { name: 'Nether Brick Slab', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'nether_brick', slab: true },
  [BLOCK.DEEPSLATE_SLAB]:    { name: 'Deepslate Slab', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'deepslate', slab: true },
  // Farming blocks
  [BLOCK.FARMLAND]: { name: 'Farmland', solid: true, hardness: 0.6, tool: 'shovel', drop: BLOCK.DIRT, faces: 'farmland' },
  [BLOCK.WHEAT_0]:  { name: 'Wheat Seeds', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, drop: 263 /* SEEDS */, faces: 'wheat_0' },
  [BLOCK.WHEAT_1]:  { name: 'Wheat Sprouts', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, drop: 263 /* SEEDS */, faces: 'wheat_1' },
  [BLOCK.WHEAT_2]:  { name: 'Wheat Growing', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, drop: 263 /* SEEDS */, faces: 'wheat_2' },
  [BLOCK.WHEAT_3]:  { name: 'Wheat', solid: false, transparent: true, cutout: true, plant: true, hardness: 0, drop: 262 /* WHEAT */, faces: 'wheat_3' },
  // Campfire & lanterns
  [BLOCK.CAMPFIRE]:   { name: 'Campfire', solid: false, transparent: true, cutout: true, hardness: 2.0, luminance: 15, faces: 'campfire' },
  [BLOCK.LANTERN]:    { name: 'Lantern', solid: true, transparent: true, hardness: 3.0, luminance: 15, faces: 'lantern' },
  [BLOCK.SOUL_LANTERN]: { name: 'Soul Lantern', solid: true, transparent: true, hardness: 3.0, luminance: 10, faces: 'soul_lantern' },
  // Stairs
  [BLOCK.STONE_STAIRS]:        { name: 'Stone Stairs', solid: true, hardness: 1.5, tool: 'pickaxe', harvest: 1, faces: 'stone', stair: true },
  [BLOCK.OAK_STAIRS]:          { name: 'Oak Stairs', solid: true, hardness: 2.0, tool: 'axe', faces: 'planks', stair: true },
  [BLOCK.COBBLESTONE_STAIRS]:  { name: 'Cobblestone Stairs', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'cobblestone', stair: true },
  [BLOCK.BRICK_STAIRS]:        { name: 'Brick Stairs', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'brick', stair: true },
  [BLOCK.QUARTZ_STAIRS]:       { name: 'Quartz Stairs', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'quartz_block', stair: true },
  [BLOCK.SANDSTONE_STAIRS]:    { name: 'Sandstone Stairs', solid: true, hardness: 0.8, tool: 'pickaxe', harvest: 1, faces: 'sandstone', stair: true },
  [BLOCK.NETHER_BRICK_STAIRS]: { name: 'Nether Brick Stairs', solid: true, hardness: 2.0, tool: 'pickaxe', harvest: 1, faces: 'nether_brick', stair: true },
  [BLOCK.DEEPSLATE_STAIRS]:    { name: 'Deepslate Stairs', solid: true, hardness: 3.0, tool: 'pickaxe', harvest: 1, faces: 'deepslate', stair: true },
  // Barrel
  [BLOCK.BARREL]: { name: 'Barrel', solid: true, hardness: 2.5, tool: 'axe', faces: 'barrel' },
};

// Resolve the tile name for a given block face. dir is 'top'|'bottom'|'side'.
export function tileNameFor(blockId, dir) {
  const def = BLOCKS[blockId];
  if (!def || !def.faces) return 'stone';
  if (typeof def.faces === 'string') return def.faces;
  if (dir === 'top') return def.faces.top ?? def.faces.side ?? 'stone';
  if (dir === 'bottom') return def.faces.bottom ?? def.faces.side ?? 'stone';
  return def.faces[dir] ?? def.faces.side ?? 'stone';
}

export function tileUV(name) {
  const t = TILES[name];
  if (!t) return [0, 0];
  return t;
}

// --- survival helpers -------------------------------------------------------
// Hardness in seconds (by hand). -1 = unbreakable.
export function blockHardness(blockId) {
  const d = BLOCKS[blockId];
  return d && d.hardness != null ? d.hardness : 0;
}
// Tool that gives full speed + (if harvestable) the drop. null = any/hand.
export function blockTool(blockId) {
  const d = BLOCKS[blockId];
  return d && d.tool ? d.tool : null;
}
// Minimum tool tier (0..4) for the drop to actually spawn.
export function blockHarvestLevel(blockId) {
  const d = BLOCKS[blockId];
  return d && d.harvest != null ? d.harvest : 0;
}
// Item id to drop. `harvestLevel` is the player's tool harvest level (0 = hand).
// If the block requires a higher harvest level than the tool provides, it drops
// nothing (0). Default = the block itself; explicit `drop` overrides.
// Leaf blocks drop a matching sapling 1/10 of the time (like classic MC).
// LEAVES is shared by oak + jungle trees; default to the oak sapling.
const LEAF_SAPLING = {
  [BLOCK.LEAVES]: BLOCK.OAK_SAPLING,
  [BLOCK.DARK_OAK_LEAVES]: BLOCK.DARK_OAK_SAPLING,
  [BLOCK.BIRCH_LEAVES]: BLOCK.BIRCH_SAPLING,
  [BLOCK.SPRUCE_LEAVES]: BLOCK.SPRUCE_SAPLING,
  [BLOCK.ACACIA_LEAVES]: BLOCK.ACACIA_SAPLING,
};

export function blockDrop(blockId, harvestLevel) {
  const d = BLOCKS[blockId];
  if (!d) return blockId;
  // Harvest-level gate: if a harvest level is required and the tool is too weak,
  // the block breaks but drops nothing.
  if (d.harvest != null && d.harvest > 0) {
    if (harvestLevel == null || harvestLevel < d.harvest) return 0;
  }
  if (d.drop != null) return d.drop; // explicit drop (may be 0 for "nothing")
  if (LEAF_SAPLING[blockId]) {
    return Math.random() < 0.1 ? LEAF_SAPLING[blockId] : 0;
  }
  return blockId;                    // default: drop self
}

// Any workbench (oak + wood-type variants) counts as a crafting table.
export function isCraftingTable(blockId) {
  return blockId === BLOCK.CRAFTING
    || blockId === BLOCK.JUNGLE_CRAFTING
    || blockId === BLOCK.BIRCH_CRAFTING
    || blockId === BLOCK.SPRUCE_CRAFTING
    || blockId === BLOCK.DARK_OAK_CRAFTING
    || blockId === BLOCK.ACACIA_CRAFTING;
}

// Slab stacking: same-type slab on slab → full block
export const SLAB_TO_FULL = {
  [BLOCK.STONE_SLAB]: BLOCK.STONE,
  [BLOCK.OAK_SLAB]: BLOCK.PLANKS,
  [BLOCK.COBBLESTONE_SLAB]: BLOCK.COBBLESTONE,
  [BLOCK.BRICK_SLAB]: BLOCK.BRICK,
  [BLOCK.QUARTZ_SLAB]: BLOCK.QUARTZ_BLOCK,
  [BLOCK.SANDSTONE_SLAB]: BLOCK.SANDSTONE,
  [BLOCK.NETHER_BRICK_SLAB]: BLOCK.NETHER_BRICK,
  [BLOCK.DEEPSLATE_SLAB]: BLOCK.DEEPSLATE,
};

// Is this a stair block? (for collision)
export function isStairBlock(blockId) {
  const d = BLOCKS[blockId];
  return d && d.stair;
}

// Wire the meta lookups into items.js (avoids a circular import at module load).
import { _bindBlockMeta } from './items.js';
_bindBlockMeta({
  harvest: blockHarvestLevel,
  tool: blockTool,
});

// FerriteCore-inspired block state cache & property deduplication
const _blockStateCache = new Map();
export function getOptimizedBlockState(blockId, meta = 0) {
  const key = (blockId << 4) | (meta & 0xf);
  let cached = _blockStateCache.get(key);
  if (!cached) {
    cached = { id: blockId, meta, def: BLOCKS[blockId] || null };
    _blockStateCache.set(key, cached);
  }
  return cached;
}

// Hotbar contents (creative-style: infinite blocks).
export const HOTBAR_BLOCKS = [
  BLOCK.GRASS,
  BLOCK.DIRT,
  BLOCK.STONE,
  BLOCK.COBBLESTONE,
  BLOCK.WOOD,
  BLOCK.PLANKS,
  BLOCK.JUNGLE_PLANKS,
  BLOCK.BIRCH_PLANKS,
  BLOCK.SPRUCE_PLANKS,
  BLOCK.DARK_OAK_PLANKS,
  BLOCK.ACACIA_PLANKS,
  BLOCK.CRAFTING,
  BLOCK.JUNGLE_CRAFTING,
  BLOCK.BIRCH_CRAFTING,
  BLOCK.SPRUCE_CRAFTING,
  BLOCK.DARK_OAK_CRAFTING,
  BLOCK.ACACIA_CRAFTING,
  BLOCK.LEAVES,
  BLOCK.GLASS,
  BLOCK.SAND,
  BLOCK.SANDSTONE,
  BLOCK.MOSSY_COBBLESTONE,
  BLOCK.COBBLESTONE_WALL,
  BLOCK.NETHER_BRICK,
  BLOCK.GLASS_PANE,
  BLOCK.HAY_BLOCK,
  BLOCK.TORCH,
  BLOCK.PRISMITE_BLOCK,
  BLOCK.COAL_BLOCK,
  BLOCK.IRON_BLOCK,
  BLOCK.GOLD_BLOCK,
  BLOCK.DIAMOND_BLOCK,
  BLOCK.VOID_STONE,
  BLOCK.QUARTZ_BLOCK,
  BLOCK.EMBEROCK,
  BLOCK.VOIDSTONE,
  BLOCK.VOID_GLASS,
  BLOCK.QUICKSAND,
  BLOCK.BLOCKSCRAP,
  BLOCK.COMPRESSED_VOIDSTONE,
  BLOCK.ECHO_ORE,
  BLOCK.VOID_PORTAL,
];
